### ISSUE TITLE
Typos and suggestions for tutorial.pdf

### ISSUE THREAD

**Issue by robertf** [jesperschmidthansen/molsim#16]
tutorial.pdf is very nicely done. Please see the following minor suggestions for typos and wording:

parallization, parallizaton -> parallelization [in several places]

such introduction -> such introductions

is on the form -> is of the form

every 100 time step -> every 100 time steps
every ten time step -> every ten time steps

an-isotropic scaling -> anisotropic scaling

barostate -> barostat

particular useful -> particularly useful

short ranged -> short-range
long ranged -> long-range

are model -> are modelled

diheadral -> dihedral

simulation of model liquid toluene -> simulation of liquid toluene

in same molecule -> in the same molecule [in 2 places]

bond length, but same force -> bond lengths, but the same force

form torsion angle -> form a torsion angle

sheared memory -> shared memory

as function of number -> as a function of the number

I hope this is useful.

**Comment by jesperschmidthansen** [comment]
Hi Robertf

Once again, thanks a lot for the help here. I've made the changes you suggest. 

Jesper

**Comment by robertf** [comment]
Jesper -

You're very welcome. I'm glad to have been of help, and I'm looking forward to finding time and an excuse to play with molsim.

I've long wanted to play with both discrete-particle modelling and molecular dynamics, and from reading your document I now see molecular-dynamics modelling as 'just' an extension of discrete-particle modelling. Is that a correct statement?

- Robert
________________________________________

**Comment by jesperschmidthansen** [comment]
Hi Robert,

I have made a few introductory videos for molsim, so if you plan to play around with it you may find them helpful - even if they are rather primitive. You can find them here   
https://github.com/jesperschmidthansen/Nanoscale-Hydrodynamics-of-Simple-Systems/tree/main/Videos

In my understanding the different discrete-particle models are all coarse grained methods compared to molecular dynamics (MD). In MD we solve the eq. of motion for the single atoms/molecules which gives a lot of information about the fluid structure and dynamics. The drawback is that we only reach very small length and time scales, so it can have serious limitations. My research is actually focused on  hydrodynamics on the nano-scale, where MD is a very useful tool.

Jesper
