### ISSUE TITLE
Exit on seplib error

### ISSUE THREAD

**Issue by jesperschmidthansen** [jesperschmidthansen/molsim#3]
When seplib throws an error molsim force exit from octave

**Comment by ghost** [comment]
I have the same problem.

I used to probe the sample code in the README.md but it throws me 
an error while reading **.xyz** file using **sep_init_xyz**. It was a memory management error I suspect.

```
octave:2> molsim_demo
Opening water.xyz
sep-error -> sep_init_xyz at line 84: Error reading xyz file
```

**Comment by jesperschmidthansen** [comment]
Hi ghost,

First, thank you for reporting this! 

I think one issue here is that water.xyz and water.top is not in your search path. Of course, the example must be executable without too much hassle, so I have made some corrections to the README.md file which hopefully fix this.

Now, as you also report seplib forces GNU Octave to exit on error, this is a bigger issue. I have been looking into this, without finding a satisfactory solution. I will now do some more digging into the problem. 

By the way, I am currently focusing on GPU support. I hope this will come soon!

**Comment by jesperschmidthansen** [comment]
- In seplib there is now a way to retrieve the function call state. From this a proper error handling action can be carried out (currently these actions are partly implemented).  
- Additional checks done on the mex-file side as well (check for files etc)

The issue will be closed, and improvements are ongoing.
